### PR TITLE
Download page

### PR DESCRIPTION
**Pull request by ZeeCoder**
Solving the following issue: https://github.com/deployphp/deployer.org/issues/10

1) Added a /download page
2) Added a download button in the side-menu
3) Added a link on the homepage pointing to the download page
4) Added the version number to the homepage download button

**Screenshots**
screen shot 2015-06-03 at 16 10 12
screen shot 2015-06-03 at 16 10 04
screen shot 2015-06-03 at 16 09 52

### CODE REVIEW

**Comment by elfet** [comment]
Amazing! :) :+1: Great! Neet to test it a little bit.

**Comment by ZeeCoder** [comment]
thought so :)

**Comment by elfet** [comment]
Add http cache too.

**Comment by ZeeCoder** [comment]
It's there I think at index.php:229.
Assuming there's a readable manifest file, there'll be http caching.

Or did you mean something else?

**Comment by ZeeCoder** [comment]
Any thoughts @elfet ?

**Comment by elfet** [comment]
i see, everything correct :) Good work.

**Comment by ZeeCoder** [comment]
:+1:

**Pull request merged**
